LoadLibraries <- function(){
  library( BigVAR )
  library( readxl )
  library( lattice )
  library( strucchange )
  library( vars )
  library( psych )
  library( tseries )
  library( tidyverse )
  library( RColorBrewer )
  library( devtools )
  library( frequencyConnectedness )
  library( stats )
  library( PerformanceAnalytics )
  library( zoo )
  library( ggplot2 )
  library( igraph )
  library( extrafont )
  windowsFonts( A = windowsFont( "Times New Roman" ) )
}
